name: site
version: '0.1.0'
category: blog
synopsis: Cyprio.net website
description: >
  Cyprio.net static generator, based on Hakyll.
author: oz@cypr.io
maintainer: oz@cypr.io
github: oz/cyprio.net
license: MIT

ghc-options: -threaded -Wall

dependencies:
  - base >= 4.13
  - hakyll >= 4.15
  - process >= 1.6

executable:
  main: Main.hs
